language: go
go:
  - '1.7'
  - stable

before_install:
  - go get -u github.com/axw/gocov/gocov
  - go get -u github.com/mattn/goveralls
  - go get -u golang.org/x/tools/cmd/cover
  - go get -u github.com/alecthomas/gometalinter
  - $HOME/gopath/bin/gometalinter --install --update

script:
  - go install -v ./...
  - go test -v ./...
  - $HOME/gopath/bin/gometalinter ./... --deadline=10s
  - go test -covermode=count -coverprofile=profile.cov

after_script:
  - $HOME/gopath/bin/goveralls -coverprofile=profile.cov -service=travis-ci
